### ISSUE TITLE
Fixing adding project to statuses/prirorities/milestones/issuetypes

### ISSUE THREAD

**Issue by Pazzo92** [ftn-tim2/uks-project#25]

**Comment by szberko** [comment]
most likely this is because of the manytomany relationship.
you need to add form.save_m2m() in the view.py, like this:

`@permission_required('uks.add_project')
@login_required
def project_create(request, template_name='uks/project_form.html'):
    form = ProjectForm(request.POST or None)
    if form.is_valid():
        project = form.save(commit=False)
        project.save()
        form.save_m2m()
        return HttpResponseRedirect(reverse('uks:project_view', kwargs={'pk': project.id}))
    return render(request, template_name, {'form': form, 'form_type': 'Create'})
`
