### ISSUE TITLE
[Suggestion and open for thoughts] View Issue page should be more compact and it should have similar design like github and jira

### ISSUE THREAD

**Issue by szberko** [ftn-tim2/uks-project#30]
Suggestions:
- we can present attributes of the issue without `<li class="list-group-item">` to have more compact view.
- we can use the same spans (`<span class="label label-warning"></span>`) like on the main dashboard page to mark Status, Milestone, IssueType, Priority.
- we need a placeholder for the future images when the issue #6 will be finished
- the comment section should be present below the attributes of the issue

Feel free to share your thoughts.

**Comment by ra28** [comment]
I have finished the task under sub-paragraph 3.
