### ISSUE TITLE
Contributor can delete the owner from the contribution list

### ISSUE THREAD

**Issue by szberko** [ftn-tim2/uks-project#91]

**Comment by Pazzo92** [comment]
Not sure how to invoke this... Contributor can not edit project

**Comment by thekrushka** [comment]
describe how

**Comment by thekrushka** [comment]
the owner should not be on the contribution list in the first place.. or it can be, but not needed.
the owner has a special connection to the project, it will not lose the rights if its not a contributor.

**Comment by szberko** [comment]
I agree. We should remove the owner of the project from the Contributors list.
Will create a new issue for this.
