### ISSUE TITLE
New issue page - The Assigned to dropdown should contain just the Contributed users for the chosen project

### ISSUE THREAD

**Issue by szberko** [ftn-tim2/uks-project#93]

**Comment by thekrushka** [comment]
it is filled by the automatic form generator, we have to investigate how to limit this set of data.

**Comment by szberko** [comment]
Done. 9790151f6a499461a59bb1d7625b2aa7c0c17829

**Comment by szberko** [comment]
done a341c6274bcf2c0e1546985e03ffbff3de15a346
